@startuml
left to right direction

actor "Client Web" as Client

node "VM Ubuntu Linux (self-hosted)" as VM {

  folder "Docker" {

   node "Conteneur BrokerX" as BrockerX {
     artifact "brokerx.war" as WAR
     note right
       Spring Boot + Tomcat
       JSP Views
       Ports exposés: 8080
     end note
   }

    node "Conteneur PostgreSQL" as DB {
      database "PostgreSQL 15" as PostgresDB

    }

  }

}

' Relations
Client --> BrockerX : HTTP/HTTPS (port 8080)
BrockerX --> PostgresDB : JDBC (port 5432)

@enduml
