version: "3.9"

services:
  # --- APP SPRING BOOT ---
  brockerx:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command: mvn spring-boot:run
    depends_on:
      - db

  # --- BASE DE DONNÉES ---
  db:
    image: postgres:15
    container_name: brockerx-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- PROMETHEUS ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - brockerx

  # --- GRAFANA ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  # --- K6 (TESTS DE CHARGE) ---
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./k6:/scripts
    ports:
      - "6565:6565"
    entrypoint: [ "sleep", "infinity" ]


volumes:
  postgres_data:
  grafana_data:
