version: "3.9"

services:
  # --- APP SPRING BOOT MASTER ---
  brockerx1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
    environment:
      SPRING_PROFILES_ACTIVE: db-master,dev
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command: mvn spring-boot:run
    depends_on:
      - db

  # --- APP SPRING BOOT SLAVE ---
  brockerx2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
    environment:
      SPRING_PROFILES_ACTIVE: db-slave,dev
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    entrypoint: [ "/wait-for-it.sh", "db:5432", "--timeout=30", "--strict", "--", "mvn", "spring-boot:run" ]
    depends_on:
      - db

  # --- BASE DE DONNÉES ---
  db:
    image: postgres:15
    container_name: brockerx-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- PROMETHEUS ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - brockerx1
      - brockerx2

  # --- GRAFANA ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  # --- K6 (TESTS DE CHARGE) ---
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./k6:/scripts
    ports:
      - "6565:6565"
    entrypoint: [ "sleep", "infinity" ]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - brockerx1
      - brockerx2

volumes:
  postgres_data:
  grafana_data:
