version: "3.9"
services:
  brockerx-test:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test   # <-- force le profil test
    depends_on:
      - db-test

  db-test:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"  # évite conflit avec le db prod locale
