# =========================
# Application
# =========================
spring.application.name=BrockerX
# =========================
# JPA / Hibernate
# =========================
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# =========================
# Datasource (PostgreSQL)
# =========================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/brockerx}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:brockerx}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:brockerx}
# =========================
# HikariCP (Connection Pool)
# =========================
spring.datasource.hikari.pool-name=BrockerXHikariCP
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.initialization-fail-timeout=-1
# =========================
# Email
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=williadesgagne@gmail.com
spring.mail.password=iuti mxgf rbwv pqqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
# =========================
# Thread Pool / Async
# =========================
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=2
spring.task.execution.pool.queue-capacity=500
# =========================
# Initialisation / Health
# =========================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted
