spring.application.name=BrockerX
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=BrockerXHikariCP
spring.datasource.hikari.leak-detection-threshold=2000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=williadesgagne@gmail.com
spring.mail.password=iuti mxgf rbwv pqqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=2
spring.task.execution.pool.queue-capacity=500
