spring.application.name=BrockerX
# Spring Boot écoute sur toutes les interfaces
server.address=0.0.0.0
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/brokerx_db
spring.datasource.username=brokerx
spring.datasource.password=secret
# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=williadesgagne@gmail.com
spring.mail.password=iuti mxgf rbwv pqqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#Health
management.endpoints.web.exposure.include=health





