worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream brockerx_backend {
        server brockerx1:8080;
        server brockerx2:8080;
    }

    server {
        listen 80;

        # Swagger UI
        location /swagger-ui/ {
            proxy_pass http://brockerx_backend$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # V3 API docs
        location /v3/api-docs/ {
            proxy_pass http://brockerx_backend$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # API v1 (ou tout autre endpoint)
        location /api/ {
            proxy_pass http://brockerx_backend$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Tout le reste (frontend etc.)
        location / {
            proxy_pass http://brockerx_backend$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
