name: CI/CD BrokerX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Générer .env pour Docker
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${{ secrets.DB_NAME }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Build Maven
        run: mvn clean package -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:check


      - name: Run Unit & Integration Tests
        run: mvn verify -Dspring.profiles.active=test -Dtest="!*E2ETest"


      - name: Debug Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up -d
          docker compose -f docker-compose.test.yml ps
          docker compose -f docker-compose.test.yml logs --tail=50

      - name: Docker Compose Test Env
        run: |
          retries=0
          max_retries=24
          until nc -z localhost 8081; do
          if [ "$retries" -ge "$max_retries" ]; then
          echo "App n'a pas démarré"
          docker compose -f docker-compose.test.yml down
          exit 1
          fi
          echo "Port 8081 pas encore ouvert..."
          sleep 5
          retries=$((retries+1))
          done
          echo "Port ouvert, app probablement prête"


      - name: Run E2E Tests
        run: mvn test -Dspring.profiles.active=e2e -Dtest="*E2ETest"

      - name: Test coverage
        run: mvn jacoco:report


      - name: Teardown Test Env
        run: docker compose -f docker-compose.test.yml down

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Production
        run: |
          docker compose down || true
          docker compose up -d --build
      - name: Check Health
        run: |
          curl -f http://brockerx:8080/actuator/health || exit 1
        
