name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 1️⃣ Checkout du code
      - uses: actions/checkout@v4

      # 2️⃣ Déploiement Docker
      - name: Déploiement local
        run: |
          cd $GITHUB_WORKSPACE
          docker compose down || true
          docker compose up -d --build

          # 👇 attendre que la DB soit prête
          echo "Waiting for DB..."
          until docker exec brockerx-db pg_isready -U brokerx; do
            sleep 5
            echo "DB not ready yet..."
          done

      - name: Test déploiement
        run: curl http://localhost:8080 || echo "App pas encore prête"
