name: CI/CD BrokerX

on:
  push:
    branches: [ "restApi" ]
  pull_request:
    branches: [ "restApi" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          sudo chown -R log430:log430 ${{ github.workspace }}
          chmod -R u+rwx ${{ github.workspace }}
          rm -rf ${{ github.workspace }}/*

      - uses: actions/checkout@v4

      - name: Check Java Version
        run: java -version

      - name: Générer .env pour Docker
        run: |
          mkdir -p build
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${{ secrets.DB_NAME }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Build Maven
        run: mvn clean package -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:check


  ## CONTINUOUS DEPLOYMENT
  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Production
        run: |
          docker compose down || true
          docker compose up -d --build
      - name: Check Health
        run: |
          retries=0
          max_retries=12
          until curl -f http://localhost:8080/actuator/health; do
            if [ $retries -ge $max_retries ]; then
              echo "App pas prête après plusieurs essais"
              exit 1
            fi
              echo "Waiting for app..."
              sleep 5
              retries=$((retries+1))
          done
          echo "App prête!"

        
